version: 2
updates:
  # Enable version updates for pip dependencies every day (weekdays)
  # Check pyproject.toml, requirements.txt, requirements_dev.txt
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    labels:
      - "pip requirements"
    reviewers:
      - "Cubicpath"
    ignore:
      # Ignore all sub-dependencies listed in the requirement files
      # Everything not listed as a dependency in pyproject.toml should be here
      # Ideally, I would exclude the files themselves from dependabot, but this is not currently an option
      # See https://github.com/dependabot/dependabot-core/issues/4364 for info
      - dependency-name: "shiboken6"
      - dependency-name: "pycodestyle"
      - dependency-name: "tokenize-rt"
      - dependency-name: "classify-imports"
      - dependency-name: "GitPython"
      - dependency-name: "PyYAML"
      - dependency-name: "stevedore"
      - dependency-name: "snowballstemmer"
      - dependency-name: "astroid"
      - dependency-name: "wrapt"
      - dependency-name: "lazy-object-proxy"
      - dependency-name: "colorama"
      - dependency-name: "dill"
      - dependency-name: "isort"
      - dependency-name: "mccabe"
      - dependency-name: "platformdirs"
      - dependency-name: "tomlkit"
      - dependency-name: "tomli"
      - dependency-name: "nodeenv"
