version: 2
updates:
  # Enable version updates for pip dependencies every day (weekdays)
  # Check pyproject.toml, requirements.txt, requirements_dev.txt
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "pip requirements"
