version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check PyPI for updates every day (weekdays)
    schedule:
      interval: "daily"
